spring.application.name=slotwise

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:slotwise}
spring.datasource.username=${DB_USER:slotwise}
spring.datasource.password=${DB_PASSWORD:slotwise_dev_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:FwFS0TdZlc75jHZTklS5GMsWOMG5XbKbwUbYoXvYGWY=}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
